namespace Wisej.DemoBrowser.ComboBox
{
	partial class Features
	{
		/// <summary> 
		/// Required designer variable.
		/// </summary>
		private System.ComponentModel.IContainer components = null;

		/// <summary> 
		/// Clean up any resources being used.
		/// </summary>
		/// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
		protected override void Dispose(bool disposing)
		{
			if (disposing && (components != null))
			{
				components.Dispose();
			}
			base.Dispose(disposing);
		}

		#region Wisej Designer generated code

		/// <summary> 
		/// Required method for Designer support - do not modify 
		/// the contents of this method with the code editor.
		/// </summary>
		private void InitializeComponent()
		{
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Features));
            this.comboBox1 = new Wisej.Web.ComboBox();
            this.comboBox9 = new Wisej.Web.ComboBox();
            this.comboBox10 = new Wisej.Web.ComboBox();
            this.comboBox11 = new Wisej.Web.ComboBox();
            this.panel1 = new Wisej.Web.Panel();
            this.flowLayoutPanel1 = new Wisej.Web.FlowLayoutPanel();
            this.panel1.SuspendLayout();
            this.flowLayoutPanel1.SuspendLayout();
            this.SuspendLayout();
            // 
            // comboBox1
            // 
            this.comboBox1.Anchor = Wisej.Web.AnchorStyles.None;
            this.comboBox1.Items.AddRange(new object[] {
            "Elkhart",
            "Erie",
            "Escondido",
            "Eugene",
            "Evansville",
            "Fairfield",
            "Fargo",
            "Fayetteville",
            "Fitchburg",
            "Flint",
            "Fontana",
            "Fort Collins",
            "Fort Lauderdale",
            "Fort Smith",
            "Fort Walton Beach",
            "Fort Wayne",
            "Fort Worth",
            "Frederick",
            "Fremont",
            "Fresno",
            "Fullerton",
            "Gainesville",
            "Garden Grove",
            "Garland",
            "Gastonia",
            "Gilbert",
            "Glendale",
            "Grand Prairie",
            "Grand Rapids",
            "Grayslake",
            "Green Bay",
            "GreenBay"});
            this.comboBox1.LabelText = "Watermark";
            this.comboBox1.Location = new System.Drawing.Point(20, 19);
            this.comboBox1.Name = "comboBox1";
            this.comboBox1.ResponsiveProfiles.Add(((Wisej.Base.ResponsiveProfile)(resources.GetObject("comboBox1.ResponsiveProfiles"))));
            this.comboBox1.Size = new System.Drawing.Size(250, 53);
            this.comboBox1.TabIndex = 0;
            this.comboBox1.Watermark = "Select a Fruit";
            this.comboBox1.SelectedIndexChanged += new System.EventHandler(this.comboBox1_SelectedIndexChanged);
            // 
            // comboBox9
            // 
            this.comboBox9.Anchor = Wisej.Web.AnchorStyles.None;
            this.comboBox9.DropDownStyle = Wisej.Web.ComboBoxStyle.Simple;
            this.comboBox9.Items.AddRange(new object[] {
            "Daytona Beach",
            "Deltona",
            "Denton",
            "Denver",
            "Des Moines",
            "Detroit",
            "Downey",
            "Duluth",
            "Durham",
            "El Monte",
            "El Paso",
            "Elizabeth",
            "Elk Grove",
            "Elkhart",
            "Erie",
            "Escondido",
            "Eugene",
            "Evansville",
            "Fairfield",
            "Fargo",
            "Fayetteville",
            "Fitchburg",
            "Flint",
            "Fontana",
            "Fort Collins",
            "Fort Lauderdale",
            "Fort Smith",
            "Fort Walton Beach",
            "Fort Wayne",
            "Fort Worth",
            "Frederick",
            "Fremont",
            "Fresno",
            "Fullerton",
            "Gainesville",
            "Garden Grove",
            "Garland",
            "Gastonia",
            "Gilbert",
            "Glendale",
            "Grand Prairie",
            "Grand Rapids",
            "Grayslake",
            "Green Bay",
            "GreenBay",
            "Greensboro",
            "Greenville",
            "Gulfport-Biloxi",
            "Hagerstown",
            "Hampton",
            "Harlingen",
            "Harrisburg",
            "Hartford",
            "Havre de Grace",
            "Hayward",
            "Hemet",
            "Henderson",
            "Hesperia",
            "Hialeah",
            "Hickory",
            "High Point",
            "Hollywood",
            "Honolulu",
            "Houma",
            "Houston",
            "Howell",
            "Huntington",
            "Huntington Beach",
            "Huntsville",
            "Independence",
            "Indianapolis",
            "Inglewood",
            "Irvine",
            "Irving",
            "Jackson",
            "Jacksonville",
            "Jefferson",
            "Jersey City",
            "Johnson City",
            "Joliet",
            "Kailua",
            "Kalamazoo",
            "Kaneohe",
            "Kansas City",
            "Kennewick",
            "Kenosha",
            "Killeen",
            "Kissimmee",
            "Knoxville",
            "Lacey",
            "Lafayette",
            "Lake Charles",
            "Lakeland",
            "Lakewood",
            "Lancaster",
            "Lansing",
            "Laredo",
            "Las Cruces",
            "Las Vegas",
            "Layton",
            "Leominster",
            "Lewisville",
            "Lexington",
            "Lincoln",
            "Little Rock",
            "Long Beach",
            "Lorain",
            "Los Angeles",
            "Louisville",
            "Lowell",
            "Lubbock",
            "Macon",
            "Madison",
            "Manchester",
            "Marina",
            "Marysville",
            "McAllen",
            "McHenry",
            "Medford",
            "Melbourne",
            "Memphis",
            "Merced",
            "Mesa",
            "Mesquite",
            "Miami",
            "Milwaukee",
            "Minneapolis",
            "Miramar",
            "Mission Viejo",
            "Mobile",
            "Modesto",
            "Monroe",
            "Monterey",
            "Montgomery",
            "Moreno Valley",
            "Murfreesboro",
            "Murrieta",
            "Muskegon",
            "Myrtle Beach",
            "Naperville",
            "Naples",
            "Nashua",
            "Nashville",
            "New Bedford",
            "New Haven",
            "New London",
            "New Orleans",
            "New York",
            "New York City",
            "Newark",
            "Newburgh",
            "Newport News",
            "Norfolk",
            "Normal",
            "Norman",
            "North Charleston",
            "North Las Vegas",
            "North Port",
            "Norwalk",
            "Norwich",
            "Oakland",
            "Ocala",
            "Oceanside",
            "Odessa",
            "Ogden",
            "Oklahoma City",
            "Olathe",
            "Olympia",
            "Omaha",
            "Ontario",
            "Orange",
            "Orem",
            "Orlando",
            "Overland Park",
            "Oxnard",
            "Palm Bay",
            "Palm Springs",
            "Palmdale",
            "Panama City",
            "Pasadena",
            "Paterson",
            "Pembroke Pines",
            "Pensacola",
            "Peoria",
            "Philadelphia",
            "Phoenix",
            "Pittsburgh",
            "Plano",
            "Pomona",
            "Pompano Beach",
            "Port Arthur",
            "Port Orange",
            "Port Saint Lucie",
            "Port St. Lucie",
            "Portland",
            "Portsmouth",
            "Poughkeepsie",
            "Providence",
            "Provo",
            "Pueblo",
            "Punta Gorda",
            "Racine",
            "Raleigh",
            "Rancho Cucamonga",
            "Reading",
            "Redding",
            "Reno",
            "Richland",
            "Richmond",
            "Richmond County",
            "Riverside",
            "Roanoke",
            "Rochester",
            "Rockford",
            "Roseville",
            "Round Lake Beach",
            "Sacramento",
            "Saginaw",
            "Saint Louis",
            "Saint Paul",
            "Saint Petersburg",
            "Salem",
            "Salinas",
            "Salt Lake City",
            "San Antonio",
            "San Bernardino",
            "San Buenaventura",
            "San Diego",
            "San Francisco",
            "San Jose",
            "Santa Ana",
            "Santa Barbara",
            "Santa Clara",
            "Santa Clarita",
            "Santa Cruz",
            "Santa Maria",
            "Santa Rosa",
            "Sarasota",
            "Savannah",
            "Scottsdale",
            "Scranton",
            "Seaside",
            "Seattle",
            "Sebastian",
            "Shreveport",
            "Simi Valley",
            "Sioux City",
            "Sioux Falls",
            "South Bend",
            "South Lyon",
            "Spartanburg",
            "Spokane",
            "Springdale",
            "Springfield",
            "St. Louis",
            "St. Paul",
            "St. Petersburg",
            "Stamford",
            "Sterling Heights",
            "Stockton",
            "Sunnyvale",
            "Syracuse",
            "Tacoma",
            "Tallahassee",
            "Tampa",
            "Temecula",
            "Tempe",
            "Thornton",
            "Thousand Oaks",
            "Toledo",
            "Topeka",
            "Torrance",
            "Trenton",
            "Tucson",
            "Tulsa",
            "Tuscaloosa",
            "Tyler",
            "Utica",
            "Vallejo",
            "Vancouver",
            "Vero Beach",
            "Victorville",
            "Virginia Beach",
            "Visalia",
            "Waco",
            "Warren",
            "Washington",
            "Waterbury",
            "Waterloo",
            "West Covina",
            "West Valley City",
            "Westminster",
            "Wichita",
            "Wilmington",
            "Winston",
            "Winter Haven",
            "Worcester",
            "Yakima"});
            this.comboBox9.LabelText = "Simple";
            this.comboBox9.Location = new System.Drawing.Point(300, 3);
            this.comboBox9.Name = "comboBox9";
            this.comboBox9.ResponsiveProfiles.Add(((Wisej.Base.ResponsiveProfile)(resources.GetObject("comboBox9.ResponsiveProfiles"))));
            this.comboBox9.Size = new System.Drawing.Size(250, 273);
            this.comboBox9.TabIndex = 10;
            // 
            // comboBox10
            // 
            this.comboBox10.Anchor = Wisej.Web.AnchorStyles.None;
            this.comboBox10.DropDownHeight = 700;
            this.comboBox10.DropDownStyle = Wisej.Web.ComboBoxStyle.DropDownList;
            this.comboBox10.Items.AddRange(new object[] {
            "Daytona Beach",
            "Deltona",
            "Denton",
            "Denver",
            "Des Moines",
            "Detroit",
            "Downey",
            "Duluth",
            "Durham",
            "El Monte",
            "El Paso",
            "Elizabeth",
            "Elk Grove",
            "Elkhart",
            "Erie",
            "Escondido",
            "Eugene",
            "Evansville",
            "Fairfield",
            "Fargo",
            "Fayetteville",
            "Fitchburg",
            "Flint",
            "Fontana",
            "Fort Collins",
            "Fort Lauderdale",
            "Fort Smith",
            "Fort Walton Beach",
            "Fort Wayne",
            "Fort Worth",
            "Frederick",
            "Fremont",
            "Fresno",
            "Fullerton",
            "Gainesville",
            "Garden Grove",
            "Garland",
            "Gastonia",
            "Gilbert",
            "Glendale",
            "Grand Prairie",
            "Grand Rapids",
            "Grayslake",
            "Green Bay",
            "GreenBay",
            "Greensboro",
            "Greenville",
            "Gulfport-Biloxi",
            "Hagerstown",
            "Hampton",
            "Harlingen",
            "Harrisburg",
            "Hartford",
            "Havre de Grace",
            "Hayward",
            "Hemet",
            "Henderson",
            "Hesperia",
            "Hialeah",
            "Hickory",
            "High Point",
            "Hollywood",
            "Honolulu",
            "Houma",
            "Houston",
            "Howell",
            "Huntington",
            "Huntington Beach",
            "Huntsville",
            "Independence",
            "Indianapolis",
            "Inglewood",
            "Irvine",
            "Irving",
            "Jackson",
            "Jacksonville",
            "Jefferson",
            "Jersey City",
            "Johnson City",
            "Joliet",
            "Kailua",
            "Kalamazoo",
            "Kaneohe",
            "Kansas City",
            "Kennewick",
            "Kenosha",
            "Killeen",
            "Kissimmee",
            "Knoxville",
            "Lacey",
            "Lafayette",
            "Lake Charles",
            "Lakeland",
            "Lakewood",
            "Lancaster",
            "Lansing",
            "Laredo",
            "Las Cruces",
            "Las Vegas",
            "Layton",
            "Leominster",
            "Lewisville",
            "Lexington",
            "Lincoln",
            "Little Rock",
            "Long Beach",
            "Lorain",
            "Los Angeles",
            "Louisville",
            "Lowell",
            "Lubbock",
            "Macon",
            "Madison",
            "Manchester",
            "Marina",
            "Marysville",
            "McAllen",
            "McHenry",
            "Medford",
            "Melbourne",
            "Memphis",
            "Merced",
            "Mesa",
            "Mesquite",
            "Miami",
            "Milwaukee",
            "Minneapolis",
            "Miramar",
            "Mission Viejo",
            "Mobile",
            "Modesto",
            "Monroe",
            "Monterey",
            "Montgomery",
            "Moreno Valley",
            "Murfreesboro",
            "Murrieta",
            "Muskegon",
            "Myrtle Beach",
            "Naperville",
            "Naples",
            "Nashua",
            "Nashville",
            "New Bedford",
            "New Haven",
            "New London",
            "New Orleans",
            "New York",
            "New York City",
            "Newark",
            "Newburgh",
            "Newport News",
            "Norfolk",
            "Normal",
            "Norman",
            "North Charleston",
            "North Las Vegas",
            "North Port",
            "Norwalk",
            "Norwich",
            "Oakland",
            "Ocala",
            "Oceanside",
            "Odessa",
            "Ogden",
            "Oklahoma City",
            "Olathe",
            "Olympia",
            "Omaha",
            "Ontario",
            "Orange",
            "Orem",
            "Orlando",
            "Overland Park",
            "Oxnard",
            "Palm Bay",
            "Palm Springs",
            "Palmdale",
            "Panama City",
            "Pasadena",
            "Paterson",
            "Pembroke Pines",
            "Pensacola",
            "Peoria",
            "Philadelphia",
            "Phoenix",
            "Pittsburgh",
            "Plano",
            "Pomona",
            "Pompano Beach",
            "Port Arthur",
            "Port Orange",
            "Port Saint Lucie",
            "Port St. Lucie",
            "Portland",
            "Portsmouth",
            "Poughkeepsie",
            "Providence",
            "Provo",
            "Pueblo",
            "Punta Gorda",
            "Racine",
            "Raleigh",
            "Rancho Cucamonga",
            "Reading",
            "Redding",
            "Reno",
            "Richland",
            "Richmond",
            "Richmond County",
            "Riverside",
            "Roanoke",
            "Rochester",
            "Rockford",
            "Roseville",
            "Round Lake Beach",
            "Sacramento",
            "Saginaw",
            "Saint Louis",
            "Saint Paul",
            "Saint Petersburg",
            "Salem",
            "Salinas",
            "Salt Lake City",
            "San Antonio",
            "San Bernardino",
            "San Buenaventura",
            "San Diego",
            "San Francisco",
            "San Jose",
            "Santa Ana",
            "Santa Barbara",
            "Santa Clara",
            "Santa Clarita",
            "Santa Cruz",
            "Santa Maria",
            "Santa Rosa",
            "Sarasota",
            "Savannah",
            "Scottsdale",
            "Scranton",
            "Seaside",
            "Seattle",
            "Sebastian",
            "Shreveport",
            "Simi Valley",
            "Sioux City",
            "Sioux Falls",
            "South Bend",
            "South Lyon",
            "Spartanburg",
            "Spokane",
            "Springdale",
            "Springfield",
            "St. Louis",
            "St. Paul",
            "St. Petersburg",
            "Stamford",
            "Sterling Heights",
            "Stockton",
            "Sunnyvale",
            "Syracuse",
            "Tacoma",
            "Tallahassee",
            "Tampa",
            "Temecula",
            "Tempe",
            "Thornton",
            "Thousand Oaks",
            "Toledo",
            "Topeka",
            "Torrance",
            "Trenton",
            "Tucson",
            "Tulsa",
            "Tuscaloosa",
            "Tyler",
            "Utica",
            "Vallejo",
            "Vancouver",
            "Vero Beach",
            "Victorville",
            "Virginia Beach",
            "Visalia",
            "Waco",
            "Warren",
            "Washington",
            "Waterbury",
            "Waterloo",
            "West Covina",
            "West Valley City",
            "Westminster",
            "Wichita",
            "Wilmington",
            "Winston",
            "Winter Haven",
            "Worcester",
            "Yakima"});
            this.comboBox10.LabelText = "Large Drop Down List";
            this.comboBox10.Location = new System.Drawing.Point(20, 110);
            this.comboBox10.Name = "comboBox10";
            this.comboBox10.ResponsiveProfiles.Add(((Wisej.Base.ResponsiveProfile)(resources.GetObject("comboBox10.ResponsiveProfiles"))));
            this.comboBox10.Size = new System.Drawing.Size(250, 53);
            this.comboBox10.TabIndex = 1;
            // 
            // comboBox11
            // 
            this.comboBox11.Anchor = Wisej.Web.AnchorStyles.None;
            this.comboBox11.DropDownStyle = Wisej.Web.ComboBoxStyle.DropDownList;
            this.comboBox11.DropDownWidth = 100;
            this.comboBox11.Items.AddRange(new object[] {
            "Daytona Beach",
            "Deltona",
            "Denton",
            "Denver",
            "Des Moines",
            "Detroit",
            "Downey",
            "Duluth",
            "Durham",
            "El Monte",
            "El Paso",
            "Elizabeth",
            "Elk Grove",
            "Elkhart",
            "Erie",
            "Escondido",
            "Eugene",
            "Evansville",
            "Fairfield",
            "Fargo",
            "Fayetteville",
            "Fitchburg",
            "Flint",
            "Fontana",
            "Fort Collins",
            "Fort Lauderdale",
            "Fort Smith",
            "Fort Walton Beach",
            "Fort Wayne",
            "Fort Worth",
            "Frederick",
            "Fremont",
            "Fresno",
            "Fullerton",
            "Gainesville",
            "Garden Grove",
            "Garland",
            "Gastonia",
            "Gilbert",
            "Glendale",
            "Grand Prairie",
            "Grand Rapids",
            "Grayslake",
            "Green Bay",
            "GreenBay",
            "Greensboro",
            "Greenville",
            "Gulfport-Biloxi",
            "Hagerstown",
            "Hampton",
            "Harlingen",
            "Harrisburg",
            "Hartford",
            "Havre de Grace",
            "Hayward",
            "Hemet",
            "Henderson",
            "Hesperia",
            "Hialeah",
            "Hickory",
            "High Point",
            "Hollywood",
            "Honolulu",
            "Houma",
            "Houston",
            "Howell",
            "Huntington",
            "Huntington Beach",
            "Huntsville",
            "Independence",
            "Indianapolis",
            "Inglewood",
            "Irvine",
            "Irving",
            "Jackson",
            "Jacksonville",
            "Jefferson",
            "Jersey City",
            "Johnson City",
            "Joliet",
            "Kailua",
            "Kalamazoo",
            "Kaneohe",
            "Kansas City",
            "Kennewick",
            "Kenosha",
            "Killeen",
            "Kissimmee",
            "Knoxville",
            "Lacey",
            "Lafayette",
            "Lake Charles",
            "Lakeland",
            "Lakewood",
            "Lancaster",
            "Lansing",
            "Laredo",
            "Las Cruces",
            "Las Vegas",
            "Layton",
            "Leominster",
            "Lewisville",
            "Lexington",
            "Lincoln",
            "Little Rock",
            "Long Beach",
            "Lorain",
            "Los Angeles",
            "Louisville",
            "Lowell",
            "Lubbock",
            "Macon",
            "Madison",
            "Manchester",
            "Marina",
            "Marysville",
            "McAllen",
            "McHenry",
            "Medford",
            "Melbourne",
            "Memphis",
            "Merced",
            "Mesa",
            "Mesquite",
            "Miami",
            "Milwaukee",
            "Minneapolis",
            "Miramar",
            "Mission Viejo",
            "Mobile",
            "Modesto",
            "Monroe",
            "Monterey",
            "Montgomery",
            "Moreno Valley",
            "Murfreesboro",
            "Murrieta",
            "Muskegon",
            "Myrtle Beach",
            "Naperville",
            "Naples",
            "Nashua",
            "Nashville",
            "New Bedford",
            "New Haven",
            "New London",
            "New Orleans",
            "New York",
            "New York City",
            "Newark",
            "Newburgh",
            "Newport News",
            "Norfolk",
            "Normal",
            "Norman",
            "North Charleston",
            "North Las Vegas",
            "North Port",
            "Norwalk",
            "Norwich",
            "Oakland",
            "Ocala",
            "Oceanside",
            "Odessa",
            "Ogden",
            "Oklahoma City",
            "Olathe",
            "Olympia",
            "Omaha",
            "Ontario",
            "Orange",
            "Orem",
            "Orlando",
            "Overland Park",
            "Oxnard",
            "Palm Bay",
            "Palm Springs",
            "Palmdale",
            "Panama City",
            "Pasadena",
            "Paterson",
            "Pembroke Pines",
            "Pensacola",
            "Peoria",
            "Philadelphia",
            "Phoenix",
            "Pittsburgh",
            "Plano",
            "Pomona",
            "Pompano Beach",
            "Port Arthur",
            "Port Orange",
            "Port Saint Lucie",
            "Port St. Lucie",
            "Portland",
            "Portsmouth",
            "Poughkeepsie",
            "Providence",
            "Provo",
            "Pueblo",
            "Punta Gorda",
            "Racine",
            "Raleigh",
            "Rancho Cucamonga",
            "Reading",
            "Redding",
            "Reno",
            "Richland",
            "Richmond",
            "Richmond County",
            "Riverside",
            "Roanoke",
            "Rochester",
            "Rockford",
            "Roseville",
            "Round Lake Beach",
            "Sacramento",
            "Saginaw",
            "Saint Louis",
            "Saint Paul",
            "Saint Petersburg",
            "Salem",
            "Salinas",
            "Salt Lake City",
            "San Antonio",
            "San Bernardino",
            "San Buenaventura",
            "San Diego",
            "San Francisco",
            "San Jose",
            "Santa Ana",
            "Santa Barbara",
            "Santa Clara",
            "Santa Clarita",
            "Santa Cruz",
            "Santa Maria",
            "Santa Rosa",
            "Sarasota",
            "Savannah",
            "Scottsdale",
            "Scranton",
            "Seaside",
            "Seattle",
            "Sebastian",
            "Shreveport",
            "Simi Valley",
            "Sioux City",
            "Sioux Falls",
            "South Bend",
            "South Lyon",
            "Spartanburg",
            "Spokane",
            "Springdale",
            "Springfield",
            "St. Louis",
            "St. Paul",
            "St. Petersburg",
            "Stamford",
            "Sterling Heights",
            "Stockton",
            "Sunnyvale",
            "Syracuse",
            "Tacoma",
            "Tallahassee",
            "Tampa",
            "Temecula",
            "Tempe",
            "Thornton",
            "Thousand Oaks",
            "Toledo",
            "Topeka",
            "Torrance",
            "Trenton",
            "Tucson",
            "Tulsa",
            "Tuscaloosa",
            "Tyler",
            "Utica",
            "Vallejo",
            "Vancouver",
            "Vero Beach",
            "Victorville",
            "Virginia Beach",
            "Visalia",
            "Waco",
            "Warren",
            "Washington",
            "Waterbury",
            "Waterloo",
            "West Covina",
            "West Valley City",
            "Westminster",
            "Wichita",
            "Wilmington",
            "Winston",
            "Winter Haven",
            "Worcester",
            "Yakima"});
            this.comboBox11.LabelText = "Skinny Drop Down List";
            this.comboBox11.Location = new System.Drawing.Point(20, 201);
            this.comboBox11.Name = "comboBox11";
            this.comboBox11.ResponsiveProfiles.Add(((Wisej.Base.ResponsiveProfile)(resources.GetObject("comboBox11.ResponsiveProfiles"))));
            this.comboBox11.Size = new System.Drawing.Size(250, 53);
            this.comboBox11.TabIndex = 2;
            // 
            // panel1
            // 
            this.panel1.Controls.Add(this.comboBox11);
            this.panel1.Controls.Add(this.comboBox10);
            this.panel1.Controls.Add(this.comboBox1);
            this.panel1.Location = new System.Drawing.Point(3, 3);
            this.panel1.Name = "panel1";
            this.panel1.ResponsiveProfiles.Add(((Wisej.Base.ResponsiveProfile)(resources.GetObject("panel1.ResponsiveProfiles"))));
            this.panel1.Size = new System.Drawing.Size(291, 273);
            this.panel1.TabIndex = 11;
            // 
            // flowLayoutPanel1
            // 
            this.flowLayoutPanel1.Anchor = Wisej.Web.AnchorStyles.None;
            this.flowLayoutPanel1.AutoScroll = true;
            this.flowLayoutPanel1.Controls.Add(this.panel1);
            this.flowLayoutPanel1.Controls.Add(this.comboBox9);
            this.flowLayoutPanel1.Location = new System.Drawing.Point(422, 98);
            this.flowLayoutPanel1.Name = "flowLayoutPanel1";
            this.flowLayoutPanel1.ResponsiveProfiles.Add(((Wisej.Base.ResponsiveProfile)(resources.GetObject("flowLayoutPanel1.ResponsiveProfiles"))));
            this.flowLayoutPanel1.ScrollBars = Wisej.Web.ScrollBars.None;
            this.flowLayoutPanel1.Size = new System.Drawing.Size(578, 279);
            this.flowLayoutPanel1.TabIndex = 12;
            // 
            // Features
            // 
            this.Controls.Add(this.flowLayoutPanel1);
            this.Name = "Features";
            this.panel1.ResumeLayout(false);
            this.panel1.PerformLayout();
            this.flowLayoutPanel1.ResumeLayout(false);
            this.flowLayoutPanel1.PerformLayout();
            this.ResumeLayout(false);

		}

		#endregion

		private Web.ComboBox comboBox1;
		private Web.ComboBox comboBox9;
		private Web.ComboBox comboBox10;
		private Web.ComboBox comboBox11;
        private Web.Panel panel1;
        private Web.FlowLayoutPanel flowLayoutPanel1;
    }
}
