name: Sync to Azure DevOps

on:
  push:
    branches:
      - main # or any branch you want to track

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout GitHub repository
      uses: actions/checkout@v3

    - name: Push to Azure DevOps
      run: |
        git remote add azure https://$(ADO_PAT):$(ADO_PAT)@dev.azure.com/iceteagroup/Wisej.NET%20DemoBrowser/_git/wisej-demobrowser
        git push azure main

    env:
      AZURE_PAT: ${{ secrets.ADO_PAT }} # Store Azure DevOps Personal Access Token (PAT) in GitHub Secrets
      AZURE_USERNAME: ${{ secrets.ADO_USERNAME }} # Store Azure DevOps Personal Access Token (PAT) in GitHub Secrets
